---
title: "Workflow"
author: "JalilRT"
date: "2022-09-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Preprocessing of DWI-HARDI images

```{r message=FALSE, warning=FALSE, engine = 'bash', eval = FALSE}

#!/bin/bash
# Use current working directory
#$ -wd /mnt/MD1200B/egarza/public/addimex_tms/derivatives/MRtrix3-v3.0_RC3/code/stdoutANDstderr_NodesUsed
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N trial_dwipreproc
#
# Number of subjects and maximum of concurrent tasks (-tc 5)
#$ -t 1-2
#
# Send an email only when there is an aborted task
#$ -m a
#$ -M victorissa.93@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load gcc/8.3.0
module load fsl/6.0.3
module load mrtrix3/3.0_RC3
module load ants/2.3.4
module load python37/3.7.6
#
# Write your commands in the next line
sub_list=($(ls -d /mnt/MD1200B/egarza/public/addimex_tms/data/bids/sub-*/ses-t0/dwi/sub-*_ses-t0_dwi.nii.gz | cut -d '/' -f 9))
export current_sub=${sub_list[$SGE_TASK_ID-1]}

cd ../../sourcedata
mkdir -p "${current_sub}/ses-t0/fmap/"
cp -r "/mnt/MD1200B/egarza/public/addimex_tms/data/bids/${current_sub}/ses-t0/dwi" "${current_sub}/ses-t0/"
cp /mnt/MD1200B/egarza/public/addimex_tms/data/bids/${current_sub}/ses-t0/fmap/*run-02* "${current_sub}/ses-t0/fmap/"
rdtime=($(cat "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.json" | grep Readout | cut -d ':' -f 2 | cut -d ' ' -f 2))
echo Running job from $current_sub
echo "ReadoutTime for dwi is $rdtime"

cd ..
mkdir -p "${current_sub}/ses-t0/fmap/"
mkdir "${current_sub}/ses-t0/dwi/"

fslroi "sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.nii.gz" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-01b0AP_dwi.nii.gz" 0 7
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 1. First 7 volumes of DWI HARDI image, which correspond to a b0 field map with PhaseEncodingDirection j- or anteroposterior AP'
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-01b0AP_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

mrmath "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-01b0AP_dwi.nii.gz" mean "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-02meanb0AP_dwi.nii.gz" -axis 3
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 2. A mean b0 field map from the first 7 volumes of DWI HARDI image, which correspond to b0 field maps with PhaseEncodingDirection j- or anteroposterior AP'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-01b0AP_dwi.nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-02meanb0AP_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

mrmath "sourcedata/${current_sub}/ses-t0/fmap/${current_sub}_ses-t0_run-02_epi.nii.gz" mean "${current_sub}/ses-t0/fmap/${current_sub}_ses-t0_run-02_space-orig_desc-03meanb0PA_epi.nii.gz" -axis 3
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_epi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 3. A mean b0 field map from the 7 field map volumes acquired for DWI HARDI image using PhaseEncodingDirection j or posteroanterior PA'
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_epi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_space-orig_desc-03meanb0PA_epi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

mrcat "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-02meanb0AP_dwi.nii.gz" "${current_sub}/ses-t0/fmap/${current_sub}_ses-t0_run-02_space-orig_desc-03meanb0PA_epi.nii.gz" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-04b0pair_dwi.nii.gz" -axis 3
python - << END
import json
from collections import OrderedDict
import os
from jsonmerge import merge
current_sub = os.environ["current_sub"]


with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file1:
	data_AP = json.load(raw_json_file1,object_pairs_hook=OrderedDict)

with open('sourcedata/'+current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_epi.json') as raw_json_file2:
	data_PA = json.load(raw_json_file2,object_pairs_hook=OrderedDict)

data = merge(data_PA,data_AP)

data['Description'] = 'Output 4. A b0 pair field map (1st volume = AP, 2nd volume = PA)'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-02meanb0AP_dwi.nii.gz', current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_space-orig_desc-03meanb0PA_epi..nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz','sourcedata/'+current_sub+'/ses-t0/fmap/'+current_sub+'_ses-t0_run-02_epi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-04b0pair_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

dwidenoise "sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.nii.gz" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-05denoised_dwi.nii.gz"
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 5. DWI HARDI image that has gone through noise removal by principal component analysis (PCA) using the Marchenko-Pastur (MP) universal distribution'
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-05denoised_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

mrdegibbs "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-05denoised_dwi.nii.gz" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-06unringed_dwi.nii.gz"
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 6. DWI HARDI image with Gibbs ringing artefacts removed using the method of local subvoxel-shifts'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-05denoised_dwi.nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-06unringed_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

cd "${current_sub}/ses-t0/dwi/"
dwipreproc "${current_sub}_ses-t0_space-orig_desc-06unringed_dwi.nii.gz" "${current_sub}_ses-t0_space-orig_desc-07preproc_dwi.nii.gz" -rpe_pair -se_epi "${current_sub}_ses-t0_space-orig_desc-04b0pair_dwi.nii.gz" -pe_dir 'ap' -fslgrad "../../../sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bvec" "../../../sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bval" -export_grad_mrtrix "${current_sub}_ses-t0_space-orig_desc-08mrtrixgrad_dwi.b" -readout_time $rdtime -eddy_options " --slm=linear"
cd ../../..
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 7. DWI HARDI image corrected for Eddy currents distortions, motion artifacts and susceptibility-induced EPI distortions using FSL'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-06unringed_dwi.nii.gz', current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-04b0pair_dwi.nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bvec', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bval']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-07preproc_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 8. DW gradient scheme in MRtrix format. It consists of one row per entry (i.e. per DWI volume), with each row consisting of 4 space-separated floating-point values; these correspond to [ x y z b ], where [ x y z ] are the components of the gradient vector, and b is the b-value in units of s/mm2'
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bvec', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bval']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-08mrtrixgrad_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

dwi2mask -fslgrad "sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bvec" "sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bval" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-07preproc_dwi.nii.gz" "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-orig_desc-09brain_mask.nii.gz"
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 9. A mask that includes both brain tissue and CSF obtained from all diffusion weighted and b=0 volumes'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-07preproc_dwi.nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bvec', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bval']
data['SpatialReference'] = 'orig'
data['Type'] = 'Brain'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-09brain_mask.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END

cd "${current_sub}/ses-t0/dwi/"
dwibiascorrect -ants -fslgrad "../../../sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bvec" "../../../sourcedata/${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_dwi.bval" -mask "${current_sub}_ses-t0_space-orig_desc-09brain_mask.nii.gz" "${current_sub}_ses-t0_space-orig_desc-07preproc_dwi.nii.gz" "${current_sub}_ses-t0_space-orig_desc-10unbiased_dwi.nii.gz"
cd ../../..
python - << END
import json
from collections import OrderedDict
import os
current_sub = os.environ["current_sub"]

with open('sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.json') as raw_json_file:
	data = json.load(raw_json_file,object_pairs_hook=OrderedDict)

data['Description'] = 'Output 10. DWI HARDI image with bias field correction performed using the N4 algorithm as provided in ANTs'
data['Sources'] = [current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-07preproc_dwi.nii.gz', current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-09brain_mask.nii.gz']
data['RawSources'] = ['sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.nii.gz', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bvec', 'sourcedata/'+current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_dwi.bval']
data['SpatialReference'] = 'orig'

with open(current_sub+'/ses-t0/dwi/'+current_sub+'_ses-t0_space-orig_desc-10unbiased_dwi.json', 'w') as ff:
	json.dump(data, ff,sort_keys=False, indent=4)
END


```


# Running changes in NODDI after 2 weeks rTMS

Lmer analysis for ICVF

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df_t0 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/ICVF/meanICVFinROIs_new.RDS")
subs_df_t0 <- mutate(subs_df_t0, stage = "T0")

subs_df_t1 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new_t1/ICVF_t1/meanICVFinROIs_new_t1.RDS")
subs_df_t1 <- mutate(subs_df_t1, stage = "T1")

subs_df <- rbind(subs_df_t0,subs_df_t1)

colnames(subs_df) <- c("val","rid","atlas","stage")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")
subs_df <- merge(subs_df,demographics,by = "rid")



subs_df_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df$stage.x),'T',fixed=TRUE)))
subs_df_weeks <- mutate(subs_df_weeks, X3=as.numeric(X2)*2)
subs_df$stage.x <- as.numeric(subs_df_weeks$X3)
subs_df$group[subs_df$group==1] <- "sham"
subs_df$group[subs_df$group==2] <- "active"
subs_df <- mutate(subs_df,rTMS=factor(group,levels=c("sham","active")))
subs_df <- mutate(subs_df,ICVF=val)
NODDI_demo_scale <- subs_df
scale_ylab <- "ICVF"
filename_suffix <- "ICVF_lmerTest"
ylim_inf <- 0.3
ylim_sup <- 1

#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  plot_lmer_probe <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  i=1
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(ICVF~stage.x*rTMS+q1_age+q2_edyears+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    plot_lmer_probe[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage.x, modx=rTMS,interval=TRUE,
                                              x.label="weeks", y.label=scale_ylab,
                                              main.title=k)
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/ICVF/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage.x:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL))))#,lim=c(ylim_inf,ylim_sup),
                              #ticks=list(at=c(ylim_sup-3*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-2*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-(ylim_sup-ylim_inf)/4,
                              #                ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],3),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],3),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    i=i+1
  }
  
  fit_mixed_tmp <- fit_mixed_tmp %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_effects <- names(fit_mixed_tmp) %>% map(~ emmeans::emmeans(fit_mixed_tmp[[.x]],
                                                c("stage.x","rTMS"), infer = c(T, T)) %>% 
                                                emmeans::eff_size(sigma = sigma(fit_mixed_tmp[[.x]]), 
                                                edf = df.residual(fit_mixed_tmp[[.x]]))) %>% 
    set_names(names(fit_mixed_tmp)) 
  
  
  fit_effects$vmPFC2DLPFC
  fit_effects$DLPFC2rvmPFC
  
  plot_lmer_probeICV <- plot_lmer_probe %>% set_names(names(fit_mixed_tmp))

```

Lmer analysis for OD

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df_t0 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/OD/meanODinROIs_new.RDS")
subs_df_t0 <- mutate(subs_df_t0, stage = "T0")

subs_df_t1 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new_t1/OD_t1/meanODinROIs_new_t1.RDS")
subs_df_t1 <- mutate(subs_df_t1, stage = "T1")

subs_df <- rbind(subs_df_t0,subs_df_t1)

colnames(subs_df) <- c("val","rid","atlas","stage")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")
subs_df <- merge(subs_df,demographics,by = "rid")



subs_df_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df$stage.x),'T',fixed=TRUE)))
subs_df_weeks <- mutate(subs_df_weeks, X3=as.numeric(X2)*2)
subs_df$stage.x <- as.numeric(subs_df_weeks$X3)
subs_df$group[subs_df$group==1] <- "sham"
subs_df$group[subs_df$group==2] <- "active"
subs_df <- mutate(subs_df,rTMS=factor(group,levels=c("sham","active")))
subs_df <- mutate(subs_df,OD=val)
NODDI_demo_scale <- subs_df
scale_ylab <- "OD"
filename_suffix <- "OD_lmerTest"
ylim_inf <- 0
ylim_sup <- 1

#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  plot_lmer_probe <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  i=1
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(OD~stage.x*rTMS+q1_age+q2_edyears+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    plot_lmer_probe[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage.x, modx=rTMS,interval=TRUE,
                                              x.label="weeks", y.label=scale_ylab,
                                              main.title=k)
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/OD/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage.x:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL))))#,lim=c(ylim_inf,ylim_sup),
                              #ticks=list(at=c(ylim_sup-3*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-2*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-(ylim_sup-ylim_inf)/4,
                              #                ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],3),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],3),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    i=i+1
  }
  
  fit_mixed_tmp <- fit_mixed_tmp %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_effects <- names(fit_mixed_tmp) %>% map(~ emmeans::emmeans(fit_mixed_tmp[[.x]],
                                                c("stage.x","rTMS"), infer = c(T, T)) %>% 
                                                emmeans::eff_size(sigma = sigma(fit_mixed_tmp[[.x]]), 
                                                edf = df.residual(fit_mixed_tmp[[.x]]))) %>% 
    set_names(names(fit_mixed_tmp)) 
  
  fit_effects$DLPFC2Caud
  fit_effects$DLPFC2Thal
  fit_effects$vmPFC2DLPFC

  plot_lmer_probeOD <- plot_lmer_probe %>% set_names(names(fit_mixed_tmp))

```

Lmer analysis for ISOVF

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df_t0 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/ISOVF/meanISOVFinROIs_new.RDS")
subs_df_t0 <- mutate(subs_df_t0, stage = "T0")

subs_df_t1 <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new_t1/ISOVF_t1/meanISOVFinROIs_new_t1.RDS")
subs_df_t1 <- mutate(subs_df_t1, stage = "T1")

subs_df <- rbind(subs_df_t0,subs_df_t1)

colnames(subs_df) <- c("val","rid","atlas","stage")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")
subs_df <- merge(subs_df,demographics,by = "rid")



subs_df_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df$stage.x),'T',fixed=TRUE)))
subs_df_weeks <- mutate(subs_df_weeks, X3=as.numeric(X2)*2)
subs_df$stage.x <- as.numeric(subs_df_weeks$X3)
subs_df$group[subs_df$group==1] <- "sham"
subs_df$group[subs_df$group==2] <- "active"
subs_df <- mutate(subs_df,rTMS=factor(group,levels=c("sham","active")))
subs_df <- mutate(subs_df,ISOVF=val)
NODDI_demo_scale <- subs_df
scale_ylab <- "CSF volume fraction (ISOVF)"
filename_suffix <- "ISOVF_lmerTest"
ylim_inf <- 0
ylim_sup <- 1

#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  plot_lmer_probe <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  i=1
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(ISOVF~stage.x*rTMS+q1_age+q2_edyears+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    plot_lmer_probe[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage.x, modx=rTMS,interval=TRUE,
                                              x.label="weeks", y.label=scale_ylab,
                                              main.title=k)
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("C:/Users/vissa/Documents/Universitaeten/TEC/Cl?nicas/2021/UNAM/TMS/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/ISOVF/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    print(e)
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage.x:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL))))#,lim=c(ylim_inf,ylim_sup),
                              #ticks=list(at=c(ylim_sup-3*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-2*(ylim_sup-ylim_inf)/4,
                              #                ylim_sup-(ylim_sup-ylim_inf)/4,
                              #                ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],3),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],3),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    i=i+1
  }
```

# Running baseline NODDI as a predictor of clinical outcome after rTMS

Lmer analysis for ICVF

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
#library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/ICVF/meanICVFinROIs_new.RDS")
VAS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/VAS.csv")
CCQ_N <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/CCQ-N.csv")
Inventory <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/Inventory.csv")
BIS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/BIS-11.csv")


colnames(subs_df) <- c("val","rid","atlas")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

VAS_t0t1 <- filter(VAS,(stage=='T0'|stage=='T1'))#&group==2)
CCQ_N_t0t1 <- filter(CCQ_N,(stage=='T0'|stage=='T1'))#&group==2)
Inventory_t0t1 <- filter(Inventory,(stage=='T0'|stage=='T1'))#&group==2)
BIS_t0t1 <- filter(BIS,(stage=='T0'|stage=='T1'))#&group==2)

create_pivot_table <- function(table_name,score_name){
  pt <- PivotTable$new()
  pt$addData(table_name)
  pt$addColumnDataGroups("stage")
  pt$addRowDataGroups("rid")
  pt$defineCalculation(calculationName=score_name,summariseExpression=paste("sum(",score_name,")",sep = "") )
  pt$renderPivot()
  table_VAS_t0t1 <- pt$asDataFrame()
  table_VAS_t0t1 <- mutate(table_VAS_t0t1, rid = rownames(table_VAS_t0t1))
  table_VAS_t0t1 <- subset(table_VAS_t0t1,select = -c(Total))
  table_VAS_t0t1 <- table_VAS_t0t1[!(row.names(table_VAS_t0t1) %in% "Total"), ]
  return(table_VAS_t0t1)
}
#save.image(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
#load(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")

#subs_df <- merge(subs_df, table_cocmet_COI_EXC_VAS_CCQ)
#subs_df <- mutate(subs_df,responder_final=factor(Responder,levels = c(FALSE,TRUE)))
subs_df <- merge(subs_df,demographics,by = "rid")


scale_prep <- function(NODDImetrics_AND_demo,scale_to_merge,varname){
  subs_df_t1 <- NODDImetrics_AND_demo
  subs_df_t1$stage <- "T1"
  #subs_df_t1$val <- NA
  subs_df_t0t1 <- rbind(NODDImetrics_AND_demo,subs_df_t1)
  subs_df_CCQ_N <- merge(subs_df_t0t1,scale_to_merge, by =c("rid","stage"),all.x=TRUE)
  subs_df_CCQ_N_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df_CCQ_N$stage),'T',fixed=TRUE)))
  subs_df_CCQ_N_weeks <- mutate(subs_df_CCQ_N_weeks, X3=as.numeric(X2)*2)
  subs_df_CCQ_N$stage <- as.numeric(subs_df_CCQ_N_weeks$X3)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,stage=factor(stage,levels = c(0,2)))
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==1] <- "sham"
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==2] <- "active"
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,rTMS=factor(group.x,levels=c("sham","active")))
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,ICVF=val)
  #subs_df_CCQ_N <- mutate(subs_df_VAS2,`ICVF-Z-score`=scale(val))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=group.x-1)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=factor(rTMS,levels = c(0,1)))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,val=val-min(val))
  #subs_df_CCQ_N <- mutate(subs_df_CCQ_N,scale=eval(varname))
  names(subs_df_CCQ_N)[names(subs_df_CCQ_N) == varname] <- 'scale'
  return(subs_df_CCQ_N)
}

subs_df_VAS <- scale_prep(subs_df,VAS_t0t1,"vas")
#plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
NODDI_demo_scale<-select(subs_df_VAS, rid,atlas,rTMS,stage,q1_age,q2_edyears,ICVF,scale)
NODDI_demo_scale <- arrange(NODDI_demo_scale,atlas,rid,stage, rTMS)
scale_ylab <- "Craving VAS score"
filename_suffix <- "VAS_lmerTest"
ylim_inf <- 0
ylim_sup <- 10

# subs_df_CCQ_N <- scale_prep(subs_df,CCQ_N_t0t1,"ccq_n")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-subs_df_CCQ_N
# scale_ylab <- "craving CCQnow"
# filename_suffix <- "CCQnow_lmerTest"
# ylim_inf <- 0
# ylim_sup <- 250
# 
# subs_df_BIStot <- scale_prep(subs_df,BIS_t0t1,"tot_score")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-subs_df_BIStot
# scale_ylab <- "total BIS11"
# filename_suffix <- "BIStot_lmerTest"
# ylim_inf <- 0#min(NODDI_demo_scale$scale)
# ylim_sup <- 100#max(NODDI_demo_scale$scale)


#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  #p_values <- c()
  i=1
  plot_lmer_gg <- list()
  plot_lmer_gg2 <- list()
  
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(scale~stage*ICVF*rTMS+q1_age*ICVF+q2_edyears*ICVF+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    #plot_lmer[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage, modx=rTMS,mod2=ICVF,interval=TRUE,
    #                                    mod2.values=quantile(tmp$val, c(.05, .5, .95)) ,x.label="weeks",
    #                                    y.label=scale_ylab, main.title=paste(k,"\npercentile of neurite density (ICVF)",sep=""))
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/ICVF/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    
    levs <- e$`stage:ICVF:rTMS` %>% as_tibble() %>% select(ICVF) %>% 
      c() %>% unlist()%>% as_factor() %>% levels()
    plot_lmer_gg[[i]] <- e$`stage:ICVF:rTMS` %>% as_tibble() %>% 
      mutate(ICVF = case_when(ICVF==levs[1]~paste0("ICVF = ",levs[1]),
                              ICVF==levs[2]~paste0("ICVF = ",levs[2]),
                              ICVF==levs[3]~paste0("ICVF = ",levs[3]),
                              ICVF==levs[4]~paste0("ICVF = ",levs[4]),
                              ICVF==levs[5]~paste0("ICVF = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = rTMS)) +
      geom_line() + facet_wrap(~ICVF)+ 
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=rTMS), colour=NA,alpha=0.1) +
      theme_bw() + labs(x="Weeks", y = scale_ylab) + 
      scale_color_manual(values = c("#ff7b00","#49b7fc")) +
      theme(text = element_text(size = 16))
    
    plot_lmer_gg2[[i]] <- e$`stage:ICVF:rTMS` %>% as_tibble() %>% 
      mutate(ICVF = case_when(ICVF==levs[1]~paste0("ICVF = ",levs[1]),
                            ICVF==levs[2]~paste0("ICVF = ",levs[2]),
                            ICVF==levs[3]~paste0("ICVF = ",levs[3]),
                            ICVF==levs[4]~paste0("ICVF = ",levs[4]),
                            ICVF==levs[5]~paste0("ICVF = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = ICVF)) +
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=ICVF), colour=NA,alpha=0.08) +
      geom_line() + facet_wrap(~rTMS) + 
      theme_bw() + labs(x="Weeks", y = scale_ylab) +
      scale_color_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) + 
      scale_fill_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) +
      theme(text = element_text(size = 16),legend.title = element_blank())
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage:ICVF:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL),lim=c(ylim_inf,ylim_sup),
                              ticks=list(at=c(ylim_sup-(ylim_sup-ylim_inf)/2,
                                              ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],2),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],2),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    #p_values <- c(p_values,coeffs[[i]][,"Pr(>|t|)"])
    i=i+1
  }
  
  plot_lmer_gg <- plot_lmer_gg %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  plot_lmer_gg2 <- plot_lmer_gg2 %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_mixed_tmp <- fit_mixed_tmp %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_effects <- names(fit_mixed_tmp) %>% map(~ emmeans::emmeans(fit_mixed_tmp[[.x]],
                                                c("stage","ICVF","rTMS"), infer = c(T, T)) %>% 
                                                emmeans::eff_size(sigma = sigma(fit_mixed_tmp[[.x]]), 
                                                edf = df.residual(fit_mixed_tmp[[.x]]))) %>% 
    set_names(names(fit_mixed_tmp))  
  
  fit_effects$Caud2Medulla  
  fit_effects$Caud2Palli
  fit_effects$Thal2Medulla
  fit_effects$Thal2Palli

```

Lmer analysis for OD

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
#library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/OD/meanODinROIs_new.RDS")
VAS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/VAS.csv")
CCQ_N <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/CCQ-N.csv")
Inventory <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/Inventory.csv")
BIS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/BIS-11.csv")


colnames(subs_df) <- c("val","rid","atlas")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

VAS_t0t1 <- filter(VAS,(stage=='T0'|stage=='T1'))#&group==2)
CCQ_N_t0t1 <- filter(CCQ_N,(stage=='T0'|stage=='T1'))#&group==2)
Inventory_t0t1 <- filter(Inventory,(stage=='T0'|stage=='T1'))#&group==2)
BIS_t0t1 <- filter(BIS,(stage=='T0'|stage=='T1'))#&group==2)

create_pivot_table <- function(table_name,score_name){
  pt <- PivotTable$new()
  pt$addData(table_name)
  pt$addColumnDataGroups("stage")
  pt$addRowDataGroups("rid")
  pt$defineCalculation(calculationName=score_name,summariseExpression=paste("sum(",score_name,")",sep = "") )
  pt$renderPivot()
  table_VAS_t0t1 <- pt$asDataFrame()
  table_VAS_t0t1 <- mutate(table_VAS_t0t1, rid = rownames(table_VAS_t0t1))
  table_VAS_t0t1 <- subset(table_VAS_t0t1,select = -c(Total))
  table_VAS_t0t1 <- table_VAS_t0t1[!(row.names(table_VAS_t0t1) %in% "Total"), ]
  return(table_VAS_t0t1)
}
#save.image(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
#load(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")

#subs_df <- merge(subs_df, table_cocmet_COI_EXC_VAS_CCQ)
#subs_df <- mutate(subs_df,responder_final=factor(Responder,levels = c(FALSE,TRUE)))
subs_df <- merge(subs_df,demographics,by = "rid")

scale_prep <- function(NODDImetrics_AND_demo,scale_to_merge,varname){
  subs_df_t1 <- NODDImetrics_AND_demo
  subs_df_t1$stage <- "T1"
  #subs_df_t1$val <- NA
  subs_df_t0t1 <- rbind(NODDImetrics_AND_demo,subs_df_t1)
  subs_df_CCQ_N <- merge(subs_df_t0t1,scale_to_merge, by =c("rid","stage"),all.x=TRUE)
  subs_df_CCQ_N_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df_CCQ_N$stage),'T',fixed=TRUE)))
  subs_df_CCQ_N_weeks <- mutate(subs_df_CCQ_N_weeks, X3=as.numeric(X2)*2)
  subs_df_CCQ_N$stage <- as.numeric(subs_df_CCQ_N_weeks$X3)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,stage=factor(stage,levels = c(0,2)))
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==1] <- "sham"
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==2] <- "active"
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,rTMS=factor(group.x,levels=c("sham","active")))
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,OD=val)
  #subs_df_CCQ_N <- mutate(subs_df_VAS2,`OD-Z-score`=scale(val))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=group.x-1)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=factor(rTMS,levels = c(0,1)))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,val=val-min(val))
  #subs_df_CCQ_N <- mutate(subs_df_CCQ_N,scale=eval(varname))
  names(subs_df_CCQ_N)[names(subs_df_CCQ_N) == varname] <- 'scale'
  return(subs_df_CCQ_N)
}

# subs_df_VAS <- scale_prep(subs_df,VAS_t0t1,"vas")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-select(subs_df_VAS, rid,atlas,rTMS,stage,q1_age,q2_edyears,OD,scale)
# NODDI_demo_scale <- arrange(NODDI_demo_scale,atlas,rid,stage, rTMS)
# scale_ylab <- "craving VAS"
# filename_suffix <- "VAS_lmerTest"
# ylim_inf <- 0
# ylim_sup <- 10
# 
# subs_df_CCQ_N <- scale_prep(subs_df,CCQ_N_t0t1,"ccq_n")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-subs_df_CCQ_N
# scale_ylab <- "craving CCQnow"
# filename_suffix <- "CCQnow_lmerTest"
# ylim_inf <- 0
# ylim_sup <- 250

subs_df_BIStot <- scale_prep(subs_df,BIS_t0t1,"tot_score")
#plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
NODDI_demo_scale<-subs_df_BIStot
scale_ylab <- "Total BIS-11 score"
filename_suffix <- "BIStot_lmerTest"
ylim_inf <- 0#min(NODDI_demo_scale$scale)
ylim_sup <- 100#max(NODDI_demo_scale$scale)

#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  i=1
  plot_lmer_gg <- list()
  plot_lmer_gg2 <- list()
  
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(scale~stage*OD*rTMS+q1_age*OD+q2_edyears*OD+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    #plot_lmer[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage, modx=rTMS,mod2=OD,interval=TRUE,
    #                                    mod2.values=quantile(tmp$val, c(.05, .5, .95)) ,x.label="weeks",
    #                                    y.label=scale_ylab, main.title=paste(k,"\npercentile of neurite density (OD)",sep=""))
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/OD/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    
    levs <- e$`stage:OD:rTMS` %>% as_tibble() %>% select(OD) %>% 
      c() %>% unlist()%>% as_factor() %>% levels()
    plot_lmer_gg[[i]] <- e$`stage:OD:rTMS` %>% as_tibble() %>% 
      mutate(OD = case_when(OD==levs[1]~paste0("OD = ",levs[1]),
                               OD==levs[2]~paste0("OD = ",levs[2]),
                               OD==levs[3]~paste0("OD = ",levs[3]),
                               OD==levs[4]~paste0("OD = ",levs[4]),
                               OD==levs[5]~paste0("OD = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = rTMS)) +
      geom_line() + facet_wrap(~OD)+ 
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=rTMS), colour=NA,alpha=0.08) +
      theme_bw() + labs(x="Weeks", y = scale_ylab) + 
      scale_color_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) + 
      scale_fill_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) +
      theme(text = element_text(size = 16))
    
    plot_lmer_gg2[[i]] <- e$`stage:OD:rTMS` %>% as_tibble() %>% 
      mutate(OD = case_when(OD==levs[1]~paste0("OD = ",levs[1]),
                               OD==levs[2]~paste0("OD = ",levs[2]),
                               OD==levs[3]~paste0("OD = ",levs[3]),
                               OD==levs[4]~paste0("OD = ",levs[4]),
                               OD==levs[5]~paste0("OD = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = OD)) +
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=OD), colour=NA,alpha=0.1) +
      geom_line() + facet_wrap(~rTMS)+ 
      ggthemes::scale_color_wsj() +
      theme_bw() + labs(x="Weeks", y = scale_ylab) +
      theme(text = element_text(size = 16),legend.title = element_blank())
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage:OD:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL),lim=c(ylim_inf,ylim_sup),
                              ticks=list(at=c(ylim_sup-(ylim_sup-ylim_inf)/2,
                                              ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],2),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],2),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    #p_values <- c(p_values,coeffs[[i]][,"Pr(>|t|)"])
    i=i+1
  }
  
  plot_lmer_gg <- plot_lmer_gg %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  plot_lmer_gg2 <- plot_lmer_gg2 %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_mixed_tmp <- fit_mixed_tmp %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_effects <- names(fit_mixed_tmp) %>% map(~ emmeans::emmeans(fit_mixed_tmp[[.x]],
                                                c("stage","OD","rTMS"), infer = c(T, T)) %>% 
                                                emmeans::eff_size(sigma = sigma(fit_mixed_tmp[[.x]]), 
                                                edf = df.residual(fit_mixed_tmp[[.x]]))) %>% 
    set_names(names(fit_mixed_tmp))  

  fit_effects$DLPFC2rvmPFC

```

Lmer analysis for ISOVF
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
#library(interactions)
#library(sjPlot)
library(lmerTest)


subs_df <- readRDS("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/ROIs_new/ISOVF/meanISOVFinROIs_new.RDS")
VAS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/VAS.csv")
CCQ_N <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/CCQ-N.csv")
Inventory <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/Inventory.csv")
BIS <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/BIS-11.csv")


colnames(subs_df) <- c("val","rid","atlas")
subs_ids <- data.frame(do.call('rbind', strsplit(as.character(subs_df$rid),'sub-',fixed=TRUE)))
subs_df$rid <- as.numeric(subs_ids$X2)

VAS_t0t1 <- filter(VAS,(stage=='T0'|stage=='T1'))#&group==2)
CCQ_N_t0t1 <- filter(CCQ_N,(stage=='T0'|stage=='T1'))#&group==2)
Inventory_t0t1 <- filter(Inventory,(stage=='T0'|stage=='T1'))#&group==2)
BIS_t0t1 <- filter(BIS,(stage=='T0'|stage=='T1'))#&group==2)

create_pivot_table <- function(table_name,score_name){
  pt <- PivotTable$new()
  pt$addData(table_name)
  pt$addColumnDataGroups("stage")
  pt$addRowDataGroups("rid")
  pt$defineCalculation(calculationName=score_name,summariseExpression=paste("sum(",score_name,")",sep = "") )
  pt$renderPivot()
  table_VAS_t0t1 <- pt$asDataFrame()
  table_VAS_t0t1 <- mutate(table_VAS_t0t1, rid = rownames(table_VAS_t0t1))
  table_VAS_t0t1 <- subset(table_VAS_t0t1,select = -c(Total))
  table_VAS_t0t1 <- table_VAS_t0t1[!(row.names(table_VAS_t0t1) %in% "Total"), ]
  return(table_VAS_t0t1)
}
#save.image(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
#load(file = "~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/pivot_tables.Rdata")
demographics <- read_csv("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/Addimex_clinical_Feb20/csv/DEMOGRAPHIC.csv")

subs_df <- merge(subs_df,demographics,by = "rid")

scale_prep <- function(NODDImetrics_AND_demo,scale_to_merge,varname){
  subs_df_t1 <- NODDImetrics_AND_demo
  subs_df_t1$stage <- "T1"
  #subs_df_t1$val <- NA
  subs_df_t0t1 <- rbind(NODDImetrics_AND_demo,subs_df_t1)
  subs_df_CCQ_N <- merge(subs_df_t0t1,scale_to_merge, by =c("rid","stage"),all.x=TRUE)
  subs_df_CCQ_N_weeks <- data.frame(do.call('rbind', strsplit(as.character(subs_df_CCQ_N$stage),'T',fixed=TRUE)))
  subs_df_CCQ_N_weeks <- mutate(subs_df_CCQ_N_weeks, X3=as.numeric(X2)*2)
  subs_df_CCQ_N$stage <- as.numeric(subs_df_CCQ_N_weeks$X3)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,stage=factor(stage,levels = c(0,2)))
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==1] <- "sham"
  subs_df_CCQ_N$group.x[subs_df_CCQ_N$group.x==2] <- "active"
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,rTMS=factor(group.x,levels=c("sham","active")))
  subs_df_CCQ_N <- mutate(subs_df_CCQ_N,ISOVF=val)
  #subs_df_CCQ_N <- mutate(subs_df_VAS2,`ISOVF-Z-score`=scale(val))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=group.x-1)
  #subs_df_VAS2 <- mutate(subs_df_VAS2,rTMS=factor(rTMS,levels = c(0,1)))
  #subs_df_VAS2 <- mutate(subs_df_VAS2,val=val-min(val))
  #subs_df_CCQ_N <- mutate(subs_df_CCQ_N,scale=eval(varname))
  names(subs_df_CCQ_N)[names(subs_df_CCQ_N) == varname] <- 'scale'
  return(subs_df_CCQ_N)
}

# subs_df_VAS <- scale_prep(subs_df,VAS_t0t1,"vas")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-select(subs_df_VAS, rid,atlas,rTMS,stage,q1_age,q2_edyears,ISOVF,scale)
# NODDI_demo_scale <- arrange(NODDI_demo_scale,atlas,rid,stage, rTMS)
# scale_ylab <- "craving VAS"
# filename_suffix <- "VAS_lmerTest"
# ylim_inf <- 0
# ylim_sup <- 10
# 
# subs_df_CCQ_N <- scale_prep(subs_df,CCQ_N_t0t1,"ccq_n")
# #plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
# NODDI_demo_scale<-subs_df_CCQ_N
# scale_ylab <- "craving CCQnow"
# filename_suffix <- "CCQnow_lmerTest"
# ylim_inf <- 0
# ylim_sup <- 250

subs_df_BIStot <- scale_prep(subs_df,BIS_t0t1,"tot_score")
#plotANDsavetables(subs_df_CCQ_N,"craving CCQnow","CCQnow",0,200)
NODDI_demo_scale<-subs_df_BIStot
scale_ylab <- "Total BIS-11 score"
filename_suffix <- "BIStot_lmerTest"
ylim_inf <- 0#min(NODDI_demo_scale$scale)
ylim_sup <- 100#max(NODDI_demo_scale$scale)


#plotANDsavetables <- function(NODDI_demo_scale,scale_ylab,filename_suffix,ylim_inf,ylim_sup){
 # library(lme4)
  plot_lmer <- list()
  fit_mixed_tmp <- list()
  coeffs <- list()
  coeffs_tib <- list()
  i=1
  plot_lmer_gg <- list()
  plot_lmer_gg2 <- list()
  
  for(k in sort(unique(NODDI_demo_scale$atlas))) {
    tmp <- filter(NODDI_demo_scale, atlas == k)
    fit_mixed_tmp[[i]] <- lmer(scale~stage*ISOVF*rTMS+q1_age*ISOVF+q2_edyears*ISOVF+(1|rid),data=tmp)
    #summary(fit_mixed_tmp[[i]])
    #confint(fit_mixed_tmp[i])
    # ranef(fit_mixed_tmp)
    # coef(fit_mixed_tmp)
    # predict_with_re <- predict(fit_mixed_tmp)
    #Anova(fit_mixed_tmp[[i]])
    
    #plot_lmer[[i]] <- probe_interaction(fit_mixed_tmp[[i]],pred=stage, modx=rTMS,mod2=ISOVF,interval=TRUE,
    #                                    mod2.values=quantile(tmp$val, c(.05, .5, .95)) ,x.label="weeks",
    #                                    y.label=scale_ylab, main.title=paste(k,"\npercentile of neurite density (ISOVF)",sep=""))
    #tab_model(fit_mixed_tmp[[i]],p.val = "kr", show.df = TRUE)#,
              #file=paste("~/Documents/Psilantro/NODDI_tms/postprocess_HARDI/NODDI_all/VAS_CCQnow_InstantView_plots/continuous/ISOVF/",
              #           filename_suffix,"/", k,"_",filename_suffix,".html",sep = ""))
    e <- allEffects(fit_mixed_tmp[[i]])
    
    levs <- e$`stage:ISOVF:rTMS` %>% as_tibble() %>% select(ISOVF) %>% 
      c() %>% unlist()%>% as_factor() %>% levels()
    plot_lmer_gg[[i]] <- e$`stage:ISOVF:rTMS` %>% as_tibble() %>% 
      mutate(ISOVF = case_when(ISOVF==levs[1]~paste0("ISOVF = ",levs[1]),
                              ISOVF==levs[2]~paste0("ISOVF = ",levs[2]),
                              ISOVF==levs[3]~paste0("ISOVF = ",levs[3]),
                              ISOVF==levs[4]~paste0("ISOVF = ",levs[4]),
                              ISOVF==levs[5]~paste0("ISOVF = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = rTMS)) +
      geom_line() + facet_wrap(~ISOVF)+ 
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=rTMS), colour=NA,alpha=0.08) +
      theme_bw() + labs(x="Weeks", y = scale_ylab) + 
      scale_color_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) + 
      scale_fill_manual(values = c("#1B9E77","#D95F02","#7570B3","#E7298A","#4DBBD5FF")) +
      theme(text = element_text(size = 16))
    
    plot_lmer_gg2[[i]] <- e$`stage:ISOVF:rTMS` %>% as_tibble() %>% 
      mutate(ISOVF = case_when(ISOVF==levs[1]~paste0("ISOVF = ",levs[1]),
                              ISOVF==levs[2]~paste0("ISOVF = ",levs[2]),
                              ISOVF==levs[3]~paste0("ISOVF = ",levs[3]),
                              ISOVF==levs[4]~paste0("ISOVF = ",levs[4]),
                              ISOVF==levs[5]~paste0("ISOVF = ",levs[5])) ) %>% 
      ggplot(aes(x = stage, y = fit, colour = ISOVF)) +
      geom_ribbon(aes(ymin=lower, ymax=upper,fill=ISOVF), colour=NA,alpha=0.1) +
      geom_line() + facet_wrap(~rTMS)+ 
      ggthemes::scale_color_wsj() +
      theme_bw() + labs(x="Weeks", y = scale_ylab) +
      theme(text = element_text(size = 16),legend.title = element_blank())
    #plot(e)
    plot_lmer[[i]] <-
      plot(e$`stage:ISOVF:rTMS`,multiline=TRUE,confint=TRUE,ci.style="bands",main=k,
           lattice = list(key.args=list(space="none")),
           axes = list(x=list(stage=list(lab=list(label=NULL),lim=c(0,2),ticks=list(at=c(0,2)))),
                       y=list(lab=list(label=NULL),lim=c(ylim_inf,ylim_sup),
                              ticks=list(at=c(ylim_sup-(ylim_sup-ylim_inf)/2,
                                              ylim_sup)))))
    summa <- summary(fit_mixed_tmp[[i]])
    coeffs_w_names <- summa$coefficients
    coeffs[[i]] <- coeffs_w_names
    row.names(coeffs[[i]]) <- NULL
    coeffs_tib[[i]] <- dplyr::tibble(Estimate=round(coeffs[[i]][,"Estimate"],2),
                                `Std. error`=round(coeffs[[i]][,"Std. Error"],2),
                                df=round(coeffs[[i]][,"df"],2),
                                `p-value`=round(coeffs[[i]][,"Pr(>|t|)"],3))
    #p_values <- c(p_values,coeffs[[i]][,"Pr(>|t|)"])
    i=i+1
  }
  
  plot_lmer_gg <- plot_lmer_gg %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  plot_lmer_gg2 <- plot_lmer_gg2 %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_mixed_tmp <- fit_mixed_tmp %>% set_names(sort(unique(NODDI_demo_scale$atlas)))
  
  fit_effects <- names(fit_mixed_tmp) %>% map(~ emmeans::emmeans(fit_mixed_tmp[[.x]],
                                                c("stage","ISOVF","rTMS"), infer = c(T, T)) %>% 
                                                emmeans::eff_size(sigma = sigma(fit_mixed_tmp[[.x]]), 
                                                edf = df.residual(fit_mixed_tmp[[.x]]))) %>% 
    set_names(names(fit_mixed_tmp))  
  
  fit_effects$DLPFC2rvmPFC
  fit_effects$vmPFC2DLPFC

```

# Running all analysis and plot them

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(gt)
library(hrbrthemes)
library(viridis)
library(pivottabler)
#library(normwhn.test)
#library(ggiraph)
#library(ggiraphExtra)
#library(moonBook)
library(lme4)
library(car)
library(effects)
library(interactions)
#library(sjPlot)
library(lmerTest)
library(cowplot)


Fig1A <-ggdraw() + draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/E_realnorm_avg.png")
Fig1B <-ggdraw() + draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/E_realnorm_std.png")

Fig1 <- ggarrange(Fig1A,ggplot() + theme_void(),Fig1B,ncol = 3,
                  labels = c("A","","B"), widths = c(1,0.072,1))

ggsave(Fig1,filename = "~/Documents/Psilantro/NODDI_tms/masks/images/Figure1.png",
       dpi = 300, height = 4, width = 8.5, bg = "white")


my_pal <- rcartocolor::carto_pal(n = 3, name = "Bold")
my_pal2 <- rcartocolor::carto_pal(n = 3, name = "Bold")[c(2,1,3)]

# lmm  ----------------------------------------------------------

source("~/Documents/Psilantro/NODDI_tms/NODDI-changes-by_rTMS-in_CUD/code/analysis_ICVF_final_Aim1B.R")

mod_fig_lm <- function(plote){
  plote + 
    theme_bw() + 
    theme(text = element_text(size = 20),
          legend.position="none",plot.title = element_blank(),
          axis.title.x = element_blank(),axis.text.x = element_blank())+
    scale_color_manual(values = my_pal2) +
    scale_fill_manual(values = my_pal2)
}

plots <- list()
plots$DLPFC2rvmPFC <- mod_fig_lm(plot_lmer_probeICV$DLPFC2rvmPFC$interactplot)  

plots$vmPFC2DLPFC <-  mod_fig_lm(plot_lmer_probeICV$vmPFC2DLPFC$interactplot)

source("~/Documents/Psilantro/NODDI_tms/NODDI-changes-by_rTMS-in_CUD/code/analysis_OD_final_Aim1B.R")

plotsOD <- list()
plotsOD$DLPFC2Caud <-  mod_fig_lm(plot_lmer_probeOD$DLPFC2Caud$interactplot)

plotsOD$DLPFC2Thal <- mod_fig_lm(plot_lmer_probeOD$DLPFC2Caud$interactplot)

plotsOD$vmPFC2DLPFC <- mod_fig_lm(plot_lmer_probeOD$vmPFC2DLPFC$interactplot) + 
  theme(axis.text.x = element_text(),axis.title.x = element_text()) +
  scale_x_continuous(breaks=c(0,0,0,2),labels=c("  T0","","","T1  ")) +
  labs(x="Time-point")

legend <- get_legend(plot_lmer_probeOD$vmPFC2DLPFC$interactplot+
                       scale_color_manual(values = my_pal2) +
                       scale_fill_manual(values = my_pal2) +
                       theme(legend.position="bottom",
                             text = element_text(size = 25)))

#----
library(cowplot)
DLPFC2rvmPFC <- ggdraw()+draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_DLPFC2rvmPFC_ls.png")
DLPFC2Thal <- ggdraw()+draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_DLPFC2Thal_ls.png")
vmPFC2DLPFC <- ggdraw()+draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_vmPFC2DLPFC_ls.png")
DLPFC2Caud <- ggdraw()+draw_image("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_DLPFC2Caud_ls.png")

brain <- ggarrange(DLPFC2rvmPFC+draw_label("DLPFC2rvmPFC",y = 0.8),
                   DLPFC2Thal+draw_label("DLPFC2Thal",y = 0.8),
                   vmPFC2DLPFC+draw_label("vmPFC2DLPFC",y = 0.8),
                   DLPFC2Caud+draw_label("DLPFC2Caud",y = 0.8),
                   ncol = 2,nrow = 2)

cuca1 <- ggarrange(brain,plots$DLPFC2rvmPFC,
                   plots$vmPFC2DLPFC,ncol = 3,labels = c("A","B","C")) 

cuca2 <- ggarrange(plotsOD$DLPFC2Caud,plotsOD$DLPFC2Thal,
                   plotsOD$vmPFC2DLPFC,
                   ncol = 3,common.legend = TRUE,
                   legend = "bottom",labels = c("D","E","F"))

cuca3 <- ggarrange(cuca1,cuca2,ncol = 1, common.legend = TRUE,
                   legend = "bottom")  

#-----------

cocoICV_fun <- function(region,lab){
  sup <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/superior/tck_",region,"_s.png"))
  ls <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_",region,"_ls.png"))
  ant <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/ant/tck_",region,"_a.png"))
  brain <- ggarrange(sup,ant,ls,ncol = 3)
  brain <- ggdraw(add_sub(brain, paste0(region, " tract")))
  plot_bg <- ggarrange(brain,ggplot() + theme_void(),plots[[region]],
                       ncol = 3,widths = c(1.7,0.042,1.2),
                       font.label = list(size=19),
                       labels = lab,vjust = -0.1)
}

cocoOD_fun <- function(region,lab){
  sup <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/superior/tck_",region,"_s.png"))
  ls <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/ls/tck_",region,"_ls.png"))
  ant <- ggdraw()+draw_image(paste0("~/Documents/Psilantro/NODDI_tms/masks/images/ant/tck_",region,"_a.png"))
  brain <- ggarrange(sup,ant,ls,ncol = 3)
  brain <- ggdraw(add_sub(brain, paste0(region, " tract")))
  plot_bg <- ggarrange(brain,ggplot() + theme_void(),plotsOD[[region]],
                       ncol = 3,widths = c(1.7,0.042,1.2),
                       font.label = list(size=19),
                       labels = lab,vjust = -0.1)
}

DLPFC2rvmPFC_ICV <- cocoICV_fun("DLPFC2rvmPFC",c("A1)","","A2)"))
vmPFC2DLPFC_ICV <- cocoICV_fun("vmPFC2DLPFC",c("B1)","","B2)"))

DLPFC2Caud_OD <- cocoOD_fun("DLPFC2Caud",c("C1)","","C2)"))
DLPFC2Thal_OD <- cocoOD_fun("DLPFC2Thal",c("D1)","","D2)"))
vmPFC2DLPFC_OD <- cocoOD_fun("vmPFC2DLPFC",c("E1)","","E2)"))

cuca <- ggarrange(ggplot() + theme_void(),ggplot() + theme_void(),legend,ncol = 3,widths = c(1.7,0.042,1.25))

cucamouse <- ggarrange(ggplot() + theme_void(),
                       DLPFC2rvmPFC_ICV,ggplot() + theme_void(),
                       vmPFC2DLPFC_ICV,ggplot() + theme_void(),
                       DLPFC2Caud_OD,ggplot() + theme_void(),
                       DLPFC2Thal_OD,ggplot() + theme_void(),
                       vmPFC2DLPFC_OD,cuca,
                       ncol = 1,heights = c(0.12,
                                            1.4,0.12,1.4,0.12,
                                            1.4,0.12,1.4,0.12,
                                            1.45,0.3))

cucamouse

library(svglite)
svglite(filename = "~/Documents/Psilantro/NODDI_tms/masks/images/Figure2.svg",
        height = 18,width = 14.5,bg = "white")
cucamouse
dev.off()

ggsave(filename = "~/Documents/Psilantro/NODDI_tms/masks/images/Figure2.png",
       cucamouse,dpi = 300,height = 18,width = 14.5,bg = "white",scale = 0.842)

# lmm predict ---------------------------------------------------

options(digits = 1)
source("~/Documents/Psilantro/NODDI_tms/NODDI-changes-by_rTMS-in_CUD/code/analysis_ICVF_final.R")
mod_fig <- function(plot){
  plot+theme(text = element_text(size = 24),
         axis.text.x = element_blank(),
         axis.title.y = element_text(size=18),
         axis.title.x = element_text(color="white",size = 3),
         plot.title = element_text(size = 18,color = "white"))+
    scale_color_manual(values = my_pal) +
    scale_fill_manual(values = my_pal) + 
    scale_x_continuous(breaks=c(0,0,0,2),labels=c("  T0","","","T1  "))+
    ggtitle('VAS score predicted by ICVF in Caud2Medulla')
}

plot_lmer_gg$Caud2Medulla <- mod_fig(plot_lmer_gg$Caud2Medulla) + facet_wrap(~ICVF,nrow = 1,ncol = 5)

plot_lmer_gg$Caud2Palli <- mod_fig(plot_lmer_gg$Caud2Palli) + facet_wrap(~ICVF,nrow = 1,ncol = 5)

plot_lmer_gg$Thal2Medulla <- mod_fig(plot_lmer_gg$Thal2Medulla) + facet_wrap(~ICVF,nrow = 1,ncol = 5)

plot_lmer_gg$Thal2Palli <- plot_lmer_gg$Thal2Palli+theme(text = element_text(size = 24),
                                                         axis.title.y = element_text(size=18),
                                                         plot.title = element_text(size = 18,color = "white"))+
  labs(x="Time-point")+
  scale_color_manual(values = my_pal) +
  scale_fill_manual(values = my_pal)+facet_wrap(~ICVF,nrow = 1,ncol = 5)+ 
  scale_x_continuous(breaks=c(0,0,0,2),labels=c("  T0","","","T1  "))+
  ggtitle('VAS score predicted by ICVF in Thal2Palli')

cucamouse_pred <- ggarrange(plot_lmer_gg$Caud2Medulla,
                            plot_lmer_gg$Caud2Palli,
                            plot_lmer_gg$Thal2Medulla,
                            plot_lmer_gg$Thal2Palli,
                            ncol = 1,nrow = 4,common.legend = T,legend = "bottom",
                            hjust = 0,font.label = list(size=18,face='bold'),
                            labels = c("A) VAS score predicted by ICVF in Caud2Medulla",
                                       "B) VAS score predicted by ICVF in Caud2Palli",
                                       "C) VAS score predicted by ICVF in Thal2Medulla",
                                       "D) VAS score predicted by ICVF in Thal2Palli")) 

ggsave(filename = "~/Documents/Psilantro/NODDI_tms/masks/images/Figure3-2.png",
       cucamouse_pred,dpi = 300,height = 16,width = 14,bg = "white")

cucamouse_pred

#------ 
source("~/Documents/Psilantro/NODDI_tms/NODDI-changes-by_rTMS-in_CUD/code/analysis_ISOVF_final.R")
plot_lmer_ggISO <- plot_lmer_gg
source("~/Documents/Psilantro/NODDI_tms/NODDI-changes-by_rTMS-in_CUD/code/analysis_OD_final.R")
plot_lmer_ggOD <- plot_lmer_gg

plot_lmer_ggISO$DLPFC2rvmPFC <- mod_fig(plot_lmer_ggISO$DLPFC2rvmPFC) + facet_wrap(~ISOVF,nrow = 1,ncol = 5)
plot_lmer_ggISO$vmPFC2DLPFC <- mod_fig(plot_lmer_ggISO$vmPFC2DLPFC) + facet_wrap(~ISOVF,nrow = 1,ncol = 5)
plot_lmer_ggOD$DLPFC2rvmPFC <- mod_fig(plot_lmer_ggOD$DLPFC2rvmPFC) + facet_wrap(~OD,nrow = 1,ncol = 5) +
  theme(axis.text.x = element_text())

cucamouse_pred2 <- ggarrange(plot_lmer_ggISO$DLPFC2rvmPFC,
                             plot_lmer_ggISO$vmPFC2DLPFC,
                             plot_lmer_ggOD$DLPFC2rvmPFC,
                             ncol = 1,nrow = 3,common.legend = T,legend = "bottom",
                             hjust = 0,font.label = list(size=18,face='bold'),
                             labels = c("A) BIS-11 score predicted by ISOVF in DLPFC2rvmPFC",
                                        "B) BIS-11 score predicted by ISOVF in vmPFC2DLPFC",
                                        "C) BIS-11 score predicted by OD in DLPFC2rvmPFC")) 

ggsave(filename = "~/Documents/Psilantro/NODDI_tms/masks/images/Figure4-2.png",
       cucamouse_pred2,dpi = 300,height = 12,width = 14,bg = "white")

cucamouse_pred2


```
